### <p>Import numpy as `np` and print the version number.</p>

In [2]:
import numpy as np
np.__version__

'1.15.4'

### <p>How to create a 1D array?</p>

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <p>Create a 3×3 numpy array of all True’s</p>

In [6]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### <p>Extract all odd numbers from arr</p>

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### <p>Replace all odd numbers in arr with -1 without changing arr</p>

In [23]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Convert a 1D array to a 2D array with 2 rows

In [27]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Stack arrays a and b vertically

In [32]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
b = np.repeat(1,10).reshape(2, -1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### method1

In [40]:
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### method 2 

In [42]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### method 3

In [43]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Stack arrays a and b horizontally

In [50]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
b = np.repeat(1, 10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### method 1

In [55]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### Method 2

In [52]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### method 3

In [53]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [59]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [62]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Get the common items between a and b.

In [63]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [69]:
print("a = {}, b = {}".format(a,b))

a = [1 2 3 2 3 4 3 4 5 6], b = [ 7  2 10  2  7  4  9  4  9  8]


In [70]:
np.intersect1d(a, b)

array([2, 4])

### From array a remove all items present in array b

In [73]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print("a = {}, b={}".format(a, b))

a = [1 2 3 4 5], b=[5 6 7 8 9]


In [74]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [75]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

### Get the positions where elements of a and b match

In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("a = {}, b={}".format(a, b))

a = [1 2 3 2 3 4 3 4 5 6], b=[ 7  2 10  2  7  4  9  4  9  8]


In [78]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### Get all items between 5 and 10 from a

In [80]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print("a = ",a)

a =  [ 2  6  1  9 10  3 27]


#### Method 1

In [82]:
index = np.where((a >= 5)&(a<=10))
index

(array([1, 3, 4], dtype=int64),)

In [83]:
a[index]

array([ 6,  9, 10])

#### Method 2

In [85]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

#### method 3

In [86]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

### Convert the function maxx that works on two scalars, to work on two arrays.

In [4]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
pair_maxx = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_maxx(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

####  How to swap two columns in a 2d numpy array? Swap columns 1 and 2 in the array arr.

In [5]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### How to swap two rows in a 2d numpy array? Swap rows 1 and 2 in the array arr:

In [8]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### How to reverse the rows of a 2D array? Reverse the columns of a 2D array arr.

In [11]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### How to create a 2D array containing random floats between 5 and 10?

In [15]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###### method 1

In [21]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

[[6.252728   6.87319888 6.2159306 ]
 [9.31128896 8.45870009 9.00997416]
 [7.24477013 8.39915684 7.96421587]
 [5.91701102 8.36565885 8.53982266]
 [8.91468527 9.97425535 9.37255281]]


###### method 2

In [23]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.77207026 6.52379455 8.35474198]
 [8.60183882 7.77863853 6.21352533]
 [5.13436245 8.67758246 7.38340313]
 [7.25932661 5.85483221 5.81366087]
 [9.94884007 6.23588468 7.84948097]]


#### How to print only 3 decimal places in python numpy array? Print or show only 3 decimal places of the numpy array rand_arr.

In [25]:
rand_arr = np.random.random((5,3))
print(rand_arr)

[[0.13834008 0.75282587 0.44440285]
 [0.55912412 0.3301998  0.27682477]
 [0.20028106 0.46672478 0.98261942]
 [0.92010119 0.41560556 0.11061463]
 [0.45071183 0.15408394 0.24009287]]


In [26]:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.138, 0.753, 0.444],
       [0.559, 0.33 , 0.277],
       [0.2  , 0.467, 0.983],
       [0.92 , 0.416, 0.111]])