In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [9]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.subtract(arr, arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.max(arr)

10

In [21]:
a = [[1,3],[2,4]]
a

[[1, 3], [2, 4]]

In [24]:
a = np.array(a)
a

array([[1, 3],
       [2, 4]])

In [26]:
b = [[1,2],[3,4]]
b = np.array(b)
b

array([[1, 2],
       [3, 4]])

In [28]:
a * b

array([[ 1,  6],
       [ 6, 16]])

In [29]:
np.dot(a,b)

array([[10, 14],
       [14, 20]])

In [30]:
np.dot(b,a)

array([[ 5, 11],
       [11, 25]])

<p style="color: blue;">Import numpy as `np` and print the version number.</p>

In [31]:
np.__version__

'1.15.4'