<h3>List vs NumPy array</h3>

In [2]:
L = [1,2,3]
print(L)

[1, 2, 3]


In [4]:
import numpy as np
A = np.array([1,2,3])
print(A)

[1 2 3]


In [5]:
for l in L:
    print(l)

1
2
3


In [6]:
for a in A:
    print(a)

1
2
3


In [8]:
L.append(4)
L

[1, 2, 3, 4, 4]

<b style="color:red;">Numpy Array not support append method</b>

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

<h6>In List Plus(+) Operater append the another list element.</h6> 

In [11]:
L2 = L + L
print(L2)

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]


<h6>In Numpy Array + operator add the inner element of array.</h6>

In [13]:
A2 = A + A
print(A2)

[2 4 6]


In [17]:
B = np.array([1,2,3, 6, 8])
B

array([1, 2, 3, 6, 8])

In [18]:
C = np.array([1,2])
C

array([1, 2])

In [19]:
D = A + C
D

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [20]:
L * 2

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [21]:
A

array([1, 2, 3])

In [22]:
A * 2

array([2, 4, 6])

<p style="color:blue">Power of list element</p>

In [23]:
L ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

<p style="color:blue">Power of numpy array element</p>

In [24]:
A

array([1, 2, 3])

In [25]:
A ** A

array([ 1,  4, 27], dtype=int32)

In [26]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [28]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

<h4 style="color:purple">For loop vs. cosine method vs. dot function</h4>

In [33]:
a = np.array([1,2])

In [34]:
b = np.array([2,1])

In [40]:
dot = 0
for e, f in zip(a, b):
    dot += e*f
    #print(dot)
dot

4

In [41]:
c = a * b
c

array([2, 2])

In [42]:
np.sum(c)

4

In [43]:
(a*b).sum()

4

In [44]:
np.dot(a,b)

4

In [45]:
a.dot(b)

4

In [46]:
b.dot(a)

4

In [47]:
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [50]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.7999999999999998

In [51]:
angle = np.arccos(cosangle)
angle

0.6435011087932847

<h4 style="color:purple;">Vectors and Matrices</h4>
<ol>
    <li>Vector is one Dimentional object.</li>
    <li>Matrix is two dimentional objects</li>
</ol>

In [53]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [54]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [55]:
L[0]

[1, 2]

In [57]:
L[0][0]

1

In [58]:
M[0][0]

1

In [59]:
M[0,0]

1

<p style="color:violet">Matrix of NumPy</p>

In [62]:
M2 = np.matrix([[1,2],[3,4]])
M2

matrix([[1, 2],
        [3, 4]])

<p style="color:violet">Convert matrix to array</p>

In [65]:
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

<h4 style="color:purple;">Generating Matrices to Work With</h4>

In [67]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
Z100 = np.zeros([10,10])
Z100

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
O100 = np.ones((10,10))
O100

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
R = np.random.random((10,10))
R

array([[0.77573652, 0.78095347, 0.04485519, 0.00556819, 0.55727011,
        0.76620356, 0.00901541, 0.08427732, 0.82827568, 0.12451708],
       [0.45336084, 0.77745274, 0.48115199, 0.17799103, 0.5401452 ,
        0.67377308, 0.0272385 , 0.13063122, 0.35330076, 0.23252624],
       [0.35104391, 0.25242876, 0.26552569, 0.40806382, 0.72674048,
        0.444035  , 0.45160098, 0.77770235, 0.90538038, 0.40507024],
       [0.09387547, 0.46115602, 0.45458425, 0.30136561, 0.00448358,
        0.40263594, 0.93693452, 0.32173627, 0.37368105, 0.16311364],
       [0.36310806, 0.92770459, 0.96145605, 0.26990808, 0.66555909,
        0.35803302, 0.24349608, 0.14785435, 0.64968282, 0.68455321],
       [0.46608298, 0.3932303 , 0.05879427, 0.68982712, 0.68887475,
        0.20084533, 0.78368659, 0.29356552, 0.87381043, 0.72571693],
       [0.09053693, 0.82817911, 0.44137824, 0.41313415, 0.51746034,
        0.35409015, 0.27294877, 0.26859591, 0.96650672, 0.9191534 ],
       [0.02142412, 0.40784653, 0.1075001

In [76]:
G = np.random.randn(10,10)
G

array([[-0.79838353, -0.7128176 ,  0.55703802, -0.00687468,  1.00297871,
        -0.31109468, -1.35162824,  0.32592515,  0.10703059, -0.83669498],
       [-1.2574059 , -0.35277973,  0.28937063,  0.88537463,  0.04846087,
        -0.24359337, -0.81806651, -1.85110317, -1.25110322, -1.0835862 ],
       [ 1.47429238,  0.58613551,  1.10234657, -0.53579442, -1.70346062,
         1.14963734,  1.26489769,  0.46603729,  0.00865302, -0.0766543 ],
       [ 0.93371628,  0.64928973,  1.00305168,  0.46983271, -0.45344014,
        -1.42600761, -2.306457  , -0.8099384 ,  0.20285505, -0.82921663],
       [-0.19735059, -0.01894549, -0.43681395, -0.09145888,  1.00094578,
        -0.47896175, -1.08938973,  0.85018877, -0.04766251, -3.06120896],
       [ 0.19491566,  0.15840486,  0.8014554 ,  3.79650361,  0.59344248,
        -1.48936537,  1.11505284,  0.15528065,  0.084668  , -0.87828203],
       [ 0.72294737, -0.94806943,  1.45751784, -1.35831421,  1.81049376,
        -0.28434904,  1.43436877,  0.62724134

In [77]:
G.mean()

0.06459453861236271

In [78]:
G.var()

1.2613424468173087

<h4 style="color:purple">Matrix Product</h4>
<ol>
    <li>Matrix Multiplication</li>
    <li>Requirements: Inner Dimentions must match</li>
</ol>

In [81]:
M1 = np.matrix([[1,2],[3,4]])
M1

matrix([[1, 2],
        [3, 4]])

In [82]:
M2 = np.matrix([[1,2],[3,4]])
M2

matrix([[1, 2],
        [3, 4]])

M3 = np.matrix([1,2])

M3

In [84]:
product = M1 * M2
product

matrix([[ 7, 10],
        [15, 22]])

In [85]:
product2 = M1 * M3

NameError: name 'M3' is not defined

<p style="color:green">Matrix Inverse</p>

In [7]:
import numpy as np
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [10]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [12]:
np.linalg.det(A)

-2.0000000000000004